export enum UrlPart {
  BACKEND_LINK = 'http://localhost:8080/api/',
  REGISTRATION = 'registration',
  LOGIN = 'login',
  ITEMS = 'items',
  ITEM_SIZES = 'items/sizes',
  ITEM_COLORS = 'items/colors',
  USERS = 'users',
  USER = 'user',
  VERIFICATION = 'verification',
  CART = 'cart',
  ADD_ADDRESS = 'add-address',
  GET_ADDRESSES = 'get-addresses',
  REMOVE_ADDRESS = 'remove-address',
  CHANGE_PASSWORD = 'change-password',
  COMPLAINTS = 'complaints',
  MESSAGES = 'messages',
  ORDERS = 'orders',
  CREATE = '/create',
  PAYMENT = 'payment',
  SEARCH = 'search',
}
